FROM python:3.11-slim

WORKDIR /app
RUN echo "deb http://ftp.debian.org/debian bookworm main" > /etc/apt/sources.list \
 && echo "deb http://security.debian.org/debian-security bookworm-security main" >> /etc/apt/sources.list \
 && apt-get update && apt-get install -y --no-install-recommends build-essential curl \
 && rm -rf /var/lib/apt/lists/*



COPY ./requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
